from __future__ import annotations


DEFAULT_LANGUAGE = "zh"


LABELS = {
    "zh": {
        "primary_hexagram": "本卦",
        "relating_hexagram": "变卦",
        "mutual_hexagram": "互卦",
        "session": "会话",
        "summary": "摘要",
        "classic_texts": "经典文本",
        "selected_texts": "取用文本",
        "body_use": "体用",
        "line": "爻",
        "line_image": "小象",
        "item": "项",
        "value": "值",
        "hexagram": "卦",
        "upper_trigram": "上卦",
        "lower_trigram": "下卦",
        "changing_lines": "动爻",
        "image": "象",
        "method": "方法",
        "question": "问题",
        "seed": "随机种子",
        "body": "体卦",
        "use": "用卦",
        "relation": "关系",
        "methods": "方法",
        "config": "配置",
        "trigram": "八卦",
        "recent_sessions": "最近会话",
        "created": "创建时间",
        "result": "结果",
        "judgment": "卦辞",
        "tuan": "彖传",
        "image_commentary": "象传",
        "language": "语言",
        "profiles": "解释档案",
        "cases": "案例",
        "no": "无",
        "body_side_upper": "上",
        "body_side_lower": "下",
        "numbers": "数字",
        "text": "文本",
        "hour": "时辰",
        "count": "数量",
        "object": "物类",
        "person": "人物",
        "static": "静物",
        "metrics_methods": "9 种方法",
        "metrics_profiles": "3 种解释档案",
        "metrics_surfaces": "API / CLI / TUI / Web",
        "no_question_text": "无问题文本",
        "visual_primary": "本卦卦象",
        "visual_relating": "变卦卦象",
        "visual_mutual": "互卦卦象",
        "visual_transition": "本卦到变卦",
        "visual_before": "本卦",
        "visual_after": "变卦",
        "moving_rule": "动爻取用",
        "view_session_details": "查看会话详情",
    },
    "en": {
        "primary_hexagram": "Primary Hexagram",
        "relating_hexagram": "Relating Hexagram",
        "mutual_hexagram": "Mutual Hexagram",
        "session": "Session",
        "summary": "Summary",
        "classic_texts": "Classic Texts",
        "selected_texts": "Selected Texts",
        "body_use": "Body / Function",
        "line": "Line",
        "line_image": "Lesser Image",
        "item": "Item",
        "value": "Value",
        "hexagram": "Hexagram",
        "upper_trigram": "Upper Trigram",
        "lower_trigram": "Lower Trigram",
        "changing_lines": "Changing Lines",
        "image": "Figure",
        "method": "Method",
        "question": "Question",
        "seed": "Seed",
        "body": "Body",
        "use": "Function",
        "relation": "Relation",
        "methods": "Methods",
        "config": "Config",
        "trigram": "Trigram",
        "recent_sessions": "Recent Sessions",
        "created": "Created",
        "result": "Result",
        "judgment": "Judgment",
        "tuan": "Tuan Commentary",
        "image_commentary": "Image Commentary",
        "language": "Language",
        "profiles": "Profiles",
        "cases": "Cases",
        "no": "None",
        "body_side_upper": "upper",
        "body_side_lower": "lower",
        "numbers": "Numbers",
        "text": "Text",
        "hour": "Hour",
        "count": "Count",
        "object": "Object",
        "person": "Person",
        "static": "Static",
        "metrics_methods": "9 Methods",
        "metrics_profiles": "3 Interpretation Profiles",
        "metrics_surfaces": "API / CLI / TUI / Web",
        "no_question_text": "No question text",
        "visual_primary": "Primary Figure",
        "visual_relating": "Relating Figure",
        "visual_mutual": "Mutual Figure",
        "visual_transition": "Primary to Relating",
        "visual_before": "Primary",
        "visual_after": "Relating",
        "moving_rule": "Moving-Line Rule",
        "view_session_details": "View session details",
    },
}


def t(language: str, key: str) -> str:
    return LABELS.get(language, LABELS[DEFAULT_LANGUAGE]).get(key, key)
